<a href="https://colab.research.google.com/github/stepanve/colaboratory-study/blob/master/study1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
%precision 3

'%.3f'

In [0]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])

In [0]:
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [0]:
data.dtype

dtype('int64')

In [0]:
print('次元数', data.ndim)
print('要素数', data.size)

次元数 1
要素数 10


In [0]:
data * 2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [0]:
data.sort()
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
print('Min:', data.min())
print('Max:', data.max())
print('Sum:', data.sum())
print('Cum:', data.cumsum())
print('Ratio:', data.cumsum() / data.sum())

Min: 1
Max: 10
Sum: 55
Cum: [ 1  3  6 10 15 21 28 36 45 55]
Ratio: [0.018 0.055 0.109 0.182 0.273 0.382 0.509 0.655 0.818 1.   ]


In [0]:
import numpy.random as random

In [0]:
random.seed(0)

In [0]:
rnd_data = random.randn(10)

In [0]:
rnd_data

array([ 1.764,  0.4  ,  0.979,  2.241,  1.868, -0.977,  0.95 , -0.151,
       -0.103,  0.411])

In [0]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])

In [0]:
print(random.choice(data, 10))

[ 7  8  8  1  2  6  5  1  5 10]


In [0]:
print(random.choice(data, 10, replace = False))

[10  2  7  8  3  1  6  5  9  4]


In [0]:
%timeit random.choice(data, 1000)

The slowest run took 27.45 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 27.2 µs per loop


In [0]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
array1 = np.arange(9).reshape(3,3)

In [0]:
array1[0, :]

array([0, 1, 2])

In [0]:
array1[:, 0]

array([0, 3, 6])

In [0]:
array2 = np.arange(9, 18).reshape(3,3)

In [0]:
np.dot(array1, array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [0]:
array1 * array2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [0]:
np.zeros((2, 3), dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0]])

In [0]:
np.zeros((2, 3), dtype=np.float64)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
import scipy.linalg as linalg

In [0]:
from scipy.optimize import minimize_scalar

In [0]:
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])

In [0]:
print(linalg.det(matrix))

-4.0


In [0]:
print(linalg.inv(matrix))

[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [0]:
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
eig_value, eig_vector = linalg.eig(matrix)

In [0]:
eig_value

array([-1.+0.j,  2.+0.j,  2.+0.j])

In [0]:
eig_vector

array([[ 0.577,  0.816,  0.408],
       [ 0.577, -0.408, -0.816],
       [ 0.577, -0.408,  0.408]])

In [0]:
def my_function(x):
  return (x**2 + 2*x + 1)

In [0]:
from scipy.optimize import newton

In [0]:
newton(my_function, 0)

-1.000

In [0]:
import numpy as np
import scipy.linalg as linalg
from scipy.optimize import newton
matrix = np.array([[1,2,3],[1,3,2],[3,1,2]])
print(linalg.det(matrix))
print(linalg.inv(matrix))
eig_value, eig_vector = linalg.eig(matrix)
print(eig_value)
print(eig_vector)

-12.0
[[-0.33333333  0.08333333  0.41666667]
 [-0.33333333  0.58333333 -0.08333333]
 [ 0.66666667 -0.41666667 -0.08333333]]
[ 6.        +0.j -1.41421356+0.j  1.41421356+0.j]
[[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]


In [0]:
def my_function(x):
  return (x**3 + 2*x + 1)

print(newton(my_function, 0))

-0.45339765151640365


In [0]:
from pandas import Series, DataFrame

In [0]:
sample_pandas_data = Series([0,10,20,30,40,50,60,70,80,90])

In [0]:
print(sample_pandas_data)

0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int64


In [0]:
sample_pandas_index_name =Series([0,10,20,30,40,50,60,70,80,90], index=['a','b','c','d','e','f','g','h','i','j'])

In [0]:
print(sample_pandas_index_name)

a     0
b    10
c    20
d    30
e    40
f    50
g    60
h    70
i    80
j    90
dtype: int64


In [0]:
sample_pandas_index_name.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [0]:
from pandas import Series, DataFrame
import pandas as pd
attri_data1 = {'ID': ['1', '2', '3', '4', '5'],
              'Sex': ['F', 'F', 'M', 'M', 'F'],
              'Money': [1000, 2000, 500, 300, 700],
              'Name': ['Saito', 'Horie', 'Kondo', 'Kawada', 'Matsubara']}
attri_data_frame1 = DataFrame(attri_data1)

In [0]:
attri_data_frame1[attri_data_frame1.Money >= 500]

ID Sex  Money       Name
0  1   F   1000      Saito
1  2   F   2000      Horie
2  3   M    500      Kondo
4  5   F    700  Matsubara

In [0]:
attri_data_frame1.Money.mean()

900.0

In [0]:
attri_data_frame1.groupby('Sex').Money.mean()


Sex
F    1233.333333
M     400.000000
Name: Money, dtype: float64

In [0]:
attri_data_frame1.mean()

ID       2469.0
Money     900.0
dtype: float64